### PR TITLE
Adding support for ppc64le architecture

### PR DESCRIPTION
**Pull request by anandtrex**
This is done just by updating the cpuinfo.py file from upstream

TODO:
* [x] Unit tests and/or doctests in docstrings
* [x] ``tox -e py36`` passes locally
* [x] ``tox -e py27`` passes locally
* [x] Docstrings and API docs for any new/modified user-facing classes and functions
* [x] Changes documented in docs/release.rst
* [x] ``tox -e docs`` passes locally
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by alimanfoo** [comment]
Thank you @anandtrex for this. It looks like some of the Windows builds are failing to compile blosc, I haven't seen that before. I've kicked off a rebuild, will see what happens.

**Comment by anandtrex** [comment]
@alimanfoo Any ideas on why the windows build fails? I have no experience with windows at all, so I'm having some trouble interpreting the error messages.

**Comment by anandtrex** [comment]
Hi @alimanfoo Yes, in my PR, the cpuinfo.py is identical to the upstream one.

**Comment by alimanfoo** [comment]
Thinking about this some more, we should be able to install cpuinfo from pypi by including it in setup_requires. This would avoid having to vendor cpuinfo ourselves. I think it would be worth giving it a try, should reduce the maintenance burden in future.

**Comment by alimanfoo** [comment]
Regarding the CI failures, it might be worth waiting until #92 is merged then rebasing and seeing if any build failures remain.

**Comment by alimanfoo** [comment]
@zarr-developers/core-devs any objections to adding ``cpuinfo`` into ``setup_requires`` rather than vendoring?

**Comment by jakirkham** [comment]
IME `setup_requires` can be a bit flaky. Namely `pip` does not really support it and some `setuptools` versions have broken it. That said, I have used it before and if that seems like the best solution, we can do it.

A better solution would be to follow [PEP 518]( https://www.python.org/dev/peps/pep-0518/ ).

**Comment by alimanfoo** [comment]
Yeah, setup_requires is such a mess. We're using it currently for setuptools-scm, so I think I figured it kinda works, but I could be wrong. Is PEP 518 implemented yet?

**Comment by alimanfoo** [comment]
> Yeah, setup_requires is such a mess. We're using it currently for setuptools-scm, so I think I figured it kinda works, but I could be wrong. Is PEP 518 implemented yet?

Answering my own question, looks like it is [fully supported](https://pip.pypa.io/en/stable/news/) as of pip 10.

**Comment by alimanfoo** [comment]
Actually I wonder if PEP518 is implemented maybe we should give it a try.

**Comment by jakirkham** [comment]
It probably is worth trying. Was just trying to avoid feature creep within this PR. 😄

**Comment by alimanfoo** [comment]
Hi all, I've made a PR (#130) which uses setup_requires for cpuinfo. I tried using pyproject.toml but there are complications and I think it's worth waiting for further work to be completed upstream (e.g., in pip and tox). My proposal is to merge #130 instead of this PR for ease of maintenance. Please let me know if any objections.

**Comment by alimanfoo** [comment]
I've backed off #130 and think for the current release would be better to pursue this PR. I've merged in latest changes from master, will see if CI failures recur.

**Comment by alimanfoo** [comment]
OK, travis is green, but appveyor is failing on PY27. Problem is with blosc compilation, this is the error:

```
c:\projects\numcodecs\c-blosc\blosc\blosc-common.h(77) : fatal error C1083: Cannot open include file: 'immintrin.h': No such file or directory
```

Looks like this issue is similar: https://github.com/facebook/zstd/issues/9

**Comment by jakirkham** [comment]
If we make sure `__AVX2__` is undefined on Windows Visual Studio 2008, that should work.

ref: https://github.com/Blosc/c-blosc/search?q=immintrin.h&unscoped_q=immintrin.h

**Comment by alimanfoo** [comment]
Thanks @jakirkham. So would that be the same as, in setup.py, replacing:

```python
        if os.name == 'nt':
            define_macros += [('__AVX2__', 1)]
```

...with:

```python
        if os.name == 'nt' and not PY2:
            define_macros += [('__AVX2__', 1)]
```

...?

**Comment by jakirkham** [comment]
Sure, that seems reasonable.

**Comment by alimanfoo** [comment]
OK, cool, I've disabled AVX2 on PY2 windows, if CI passes I'll merge.

**Comment by alimanfoo** [comment]
Trying a better way to disable AVX2 on windows PY2...

**Pull request merged**
