### PR TITLE
Check cpuinfo only when needed.

### PR DESCRIPTION
**Pull request by QuLogic**
The cpuinfo module does not support s390x and [fails to import](https://kojipkgs.fedoraproject.org//work/tasks/9255/33639255/build.log), but we don't really need it since we've set `CFLAGS`. Move the import later so it's only used when actually checking CPU instruction support.

TODO:
* [N/A] Unit tests and/or doctests in docstrings
* [x] ``tox -e py37`` passes locally
* [ ] ``tox -e py27`` passes locally
* [N/A] Docstrings and API docs for any new/modified user-facing classes and functions
* [ ] Changes documented in docs/release.rst
* [ ] ``tox -e docs`` passes locally
* [x] AppVeyor and Travis CI passes
* [x] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by QuLogic** [comment]
Since those files require setting `-DSHUFFLE_SSE2_ENABLED` and `-DSHUFFLE_AVX`2_ENABLED`, maybe check if the user's set that in `CFLAGS`?

It's impossible to just look for a compiler option (e.g., `-msse2`), because it could be implied by any number of `-march` flags.

**Comment by jakirkham** [comment]
Would it be possible to raise this with the developers of cpuinfo?

**Comment by QuLogic** [comment]
It's known upstream: https://github.com/workhorsy/py-cpuinfo/issues/69

**Comment by jakirkham** [comment]
It seems like the developer has done some work on it (has a branch) and probably needs more people from the community with access to that architecture to engage with him and try it out. Would you mind engaging in that issue directly and sharing a bit more about what in that branch doesn’t work?

**Comment by jakirkham** [comment]
It looks like upstream addressed this issue. So I've submitted PR ( https://github.com/zarr-developers/numcodecs/pull/202 ), which merely updates `cpuinfo.py` to a commit with the needed feature. Can you please check if that is acceptable @QuLogic? If so, I'll go ahead and merge that PR.

**Pull request closed without merging**
