### PR TITLE
Update blosc version

### PR DESCRIPTION
**Pull request by dstansby**
Updates the blosc version to the latest 1.x release.

I think fixes https://github.com/zarr-developers/numcodecs/issues/429?

TODO:

- [ ] Unit tests and/or doctests in docstrings
- [ ] Tests pass locally
- [ ] Docstrings and API docs for any new/modified user-facing classes and functions
- [ ] Changes documented in docs/release.rst
- [ ] Docs build locally
- [ ] GitHub Actions CI passes
- [ ] Test coverage to 100% (Codecov passes)

### CODE REVIEW

**Comment by dstansby** [comment]
😦 doesn't seem to be working. I'll take a look and see if I can work out why

**Comment by dstansby** [comment]
I'm going to try bumping one minor release at a time from blosc 1.21.0 to 1.21.4 to help isolate the issue.

**Comment by dstansby** [comment]
I'll close this and run CI in my own fork until it's fixed so you don't have to keep approving CI here - will re-open this PR ping if/when it's fixed!

**Comment by dstansby** [comment]
Yep, just seems to be the Linux Python 3.8 jobs that are failing 😢 Error seems to be:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_LZ4=1 -DHAVE_ZLIB=1 -DHAVE_ZSTD=1 -Ic-blosc/blosc -Ic-blosc/internal-complibs/lz4-1.9.3 -Ic-blosc/internal-complibs/zlib-1.2.11 -Ic-blosc/internal-complibs/zstd-1.5.0 -Ic-blosc/internal-complibs/zlib-1.2.11/msdos -Ic-blosc/internal-complibs/zlib-1.2.11/doc -Ic-blosc/internal-complibs/zlib-1.2.11/nintendods -Ic-blosc/internal-complibs/zlib-1.2.11/qnx -Ic-blosc/internal-complibs/zlib-1.2.11/test -Ic-blosc/internal-complibs/zlib-1.2.11/amiga -Ic-blosc/internal-complibs/zlib-1.2.11/examples -Ic-blosc/internal-complibs/zlib-1.2.11/old -Ic-blosc/internal-complibs/zlib-1.2.11/os400 -Ic-blosc/internal-complibs/zlib-1.2.11/win32 -Ic-blosc/internal-complibs/zlib-1.2.11/watcom -Ic-blosc/internal-complibs/zlib-1.2.11/contrib -Ic-blosc/internal-complibs/zstd-1.5.0/compress -Ic-blosc/internal-complibs/zstd-1.5.0/decompress -Ic-blosc/internal-complibs/zstd-1.5.0/dictBuilder -Ic-blosc/internal-complibs/zstd-1.5.0/deprecated -Ic-blosc/internal-complibs/zstd-1.5.0/legacy -Ic-blosc/internal-complibs/zstd-1.5.0/common -Ic-blosc/internal-complibs/zstd-1.5.0/dll -Ic-blosc/internal-complibs/zlib-1.2.11/old/os2 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/masmx86 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/asm686 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/ada -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/dotzlib -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/iostream2 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/pascal -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/infback9 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/untgz -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/iostream -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/inflate86 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/minizip -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/iostream3 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/gcc_gvmat64 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/blast -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/puff -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/masmx64 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/vstudio -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/amd64 -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/delphi -Ic-blosc/internal-complibs/zlib-1.2.11/contrib/testzlib -Ic-blosc/internal-complibs/zstd-1.5.0/dll/example -I/opt/_internal/cpython-3.8.17/include/python3.8 -c numcodecs/blosc.c -o build/temp.linux-x86_64-cpython-38/numcodecs/blosc.o -msse2 -mno-avx2 -DSHUFFLE_SSE2_ENABLED
        In file included from /opt/_internal/cpython-3.8.17/include/python3.8/Python.h:44,
                         from numcodecs/blosc.c:151:
        c-blosc/internal-complibs/zlib-1.2.11/contrib/minizip/crypt.h:35:53: error: unknown type name ‘z_crc_t’
           35 | static int decrypt_byte(unsigned long* pkeys, const z_crc_t* pcrc_32_tab)
              |                                                     ^~~~~~~
        c-blosc/internal-complibs/zlib-1.2.11/contrib/minizip/crypt.h:48:51: error: unknown type name ‘z_crc_t’
           48 | static int update_keys(unsigned long* pkeys,const z_crc_t* pcrc_32_tab,int c)
              |                                                   ^~~~~~~
        c-blosc/internal-complibs/zlib-1.2.11/contrib/minizip/crypt.h:65:69: error: unknown type name ‘z_crc_t’
           65 | static void init_keys(const char* passwd,unsigned long* pkeys,const z_crc_t* pcrc_32_tab)
              |                                                                     ^~~~~~~
```

**Comment by mkitti** [comment]
https://github.com/zarr-developers/numcodecs/pull/500 supersedes this with all tests passing.

* It upgrades to c-blosc 1.21.5 (including Zstandard 1.5.5)
* The Python 3.8 issue is addressed by not including the minizip directory
* Assembly files are compiled on x86_64

**Pull request closed without merging**
