### PR TITLE
[CI] Just test import for wheels

### PR DESCRIPTION
**Pull request by psobolewskiPhD**
Currently, PR workflows run tests and build wheels. 
Meanwhile, the wheel workflow runs full tests again. 
This PR changes the wheel tests to just check that numcodecs is import-able, to reduce CI time.
See https://github.com/zarr-developers/numcodecs/pull/427#issuecomment-1494928538 and followup thread.

Note: could add something more to the command beyond importing, but I'm not sure what would be useful.

TODO:

- [ ] Unit tests and/or doctests in docstrings
- [ ] Tests pass locally
- [ ] Docstrings and API docs for any new/modified user-facing classes and functions
- [ ] Changes documented in docs/release.rst
- [ ] Docs build locally
- [ ] GitHub Actions CI passes
- [ ] Test coverage to 100% (Codecov passes)

### CODE REVIEW

**Comment by psobolewskiPhD** [comment]
Just a note the concurrency worked perfectly!

**Comment by psobolewskiPhD** [comment]
Wheels look like ~15 min total now:
https://github.com/zarr-developers/numcodecs/actions/runs/5702970684?pr=453
vs. 20+ on this docs update PR:
https://github.com/zarr-developers/numcodecs/actions/runs/5702663996?pr=426

**Comment by psobolewskiPhD** [comment]
The original build with arm64 macOS PR:
image
This PR:
image
Older, unrelated docs PR (no changes to wheels, no arm64 macOS)
image

Not sure the runners are reliably the same, but the testing time savings is greatest on macOS.
Python 3.8 is particularly slow BTW (and no longer supported by numpy...)

**Comment by joshmoore** [comment]
Considering msgpack, etc. were not installed by the wheels build anyway, the call to `pytest` couldn't currently have been comprehensive. I imagine there's more unification that could happen between the builds, but for the moment, this seems like a straight-forward enough simplification. :+1:

**Pull request merged**
