### PR TITLE
BLD: add newer gcc and clang to build matrix

### PR DESCRIPTION
**Pull request by llllllllll**
Adds the current latest release for gcc and clang

### CODE REVIEW

**Comment by jakirkham** [comment]
This might need to be adjusted to exclude or otherwise handle macOS.

**Comment by joshmoore** [comment]
In light of recent build updates (#320) anything here that needs resurrecting?

**Comment by jakirkham** [comment]
Don't think so.

Travis CI defaulted to fairly old compilers, but we've since moved to GitHub Actions and using conda-forge compilers, which are quite recent and regularly updated.

Also this preceded the addition of wheel builds (in addition to Conda packages, which we already had). So it is a lot easier for users to get binaries without having to build from source.

That said, certainly appreciate the effort here. It was always a bit challenging wrangling with these things on Travis. Hopefully similar issues should be easier to fix now that we manage our own dependencies (including compilers) with Conda.

**Comment by joshmoore** [comment]
Understood & agreed. Thanks from my side as well, @llllllllll. If there's anything that would help you on the GH actions front, please let us know.

**Pull request closed without merging**
