### PR TITLE
Try to migrate to Gh-action.

### PR DESCRIPTION
**Pull request by Carreau**
As we are out of time on .travis-ci for the zarr org.

[Description of PR]

TODO:
* [ ] Unit tests and/or doctests in docstrings
* [ ] ``tox -e py38`` passes locally
* [ ] Docstrings and API docs for any new/modified user-facing classes and functions
* [ ] Changes documented in docs/release.rst
* [ ] ``tox -e docs`` passes locally
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks for starting this Matthias! 😄

It looks like GitHub Actions doesn't provide us a compiler atm. Not sure how we add one. Maybe a simple solution would be to use the same image we use for wheels here. That way we are building in the same environment we later use for deployment. Though open to other ideas if you have thoughts 🙂

**Comment by Carreau** [comment]
I've tried to fix osx; but was unable to without using conda. See #266 for part of a solution.
I'm not sure if building wheels on conda is fine or not and would lead to issues on non-conda installs.

**Comment by jakirkham** [comment]
Are there changes from here that we would like to integrate as well?

**Comment by joshmoore** [comment]
There doesn't seem to be anything here that's not in https://github.com/zarr-developers/numcodecs/blob/main/.github/workflows/ci-linux.yaml

**Pull request closed without merging**
