### PR TITLE
Modify zfp source

### PR DESCRIPTION
**Pull request by halehawk**
[Added a zfp source library with a modification: variable "type" is changed to variable "_type",
to see if this change can help zfp binding passing the AppVeyor tests]

TODO:
* [x ] Unit tests and/or doctests in docstrings
* [x ] ``tox -e py37`` passes locally
* [x ] ``tox -e py27`` passes locally
* [x ] Docstrings and API docs for any new/modified user-facing classes and functions
* [x ] Changes documented in docs/release.rst
* [x ] ``tox -e docs`` passes locally
* [ ] AppVeyor and Travis CI passes
* [x ] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by halehawk** [comment]
Sure, I will look into those conflicts.

**Comment by jakirkham** [comment]
Sorry I very rarely use Windows and am a bit swamped atm. 😞

**Comment by jakirkham** [comment]
Maybe just skip Windows?

**Comment by rabernat** [comment]
The other thing unclear to me about this PR is whether the submodule has been done correctly. It looks like 148 files have been added to this repo, i.e. all of the source files for zfp. Is that how it should look?

**Comment by halehawk** [comment]
I can remove the zfp source codes. I added that for debugging purposes.

**Comment by halehawk** [comment]
I didn't see zfp source code from my fork repo. How to check zfp submodule?

**Comment by rabernat** [comment]
I can't speak for the state of your local branches, but branch this PR comes from (`halehawk:modify_zfp_source`) definitely has those files in it: https://github.com/halehawk/numcodecs/tree/modify_zfp_source/zfp-0.5.4

**Pull request closed without merging**
