### PR TITLE
Drop Python 3.7

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/zarr-developers/numcodecs/issues/381

TODO:

- [ ] Unit tests and/or doctests in docstrings
- [ ] Tests pass locally
- [ ] Docstrings and API docs for any new/modified user-facing classes and functions
- [ ] Changes documented in docs/release.rst
- [ ] Docs build locally
- [ ] GitHub Actions CI passes
- [ ] Test coverage to 100% (Codecov passes)

### CODE REVIEW

**Review by joshmoore — APPROVED** [review]
:+1:

**Comment by jakirkham** [comment]
Ha! Missed this one thing 😉 Fixing now

Screen Shot 2022-12-13 at 5 15 00 PM

**Comment by jakirkham** [comment]
Dropped Python 3.7 from required checks. Also add Python 3.10 & 3.11 to required checks.

**Comment by jakirkham** [comment]
Caught some leftover Python 3.7 compatibility code. Removing in PR ( https://github.com/zarr-developers/numcodecs/pull/406 ).

**Pull request merged**
