### PR TITLE
Be robust against cpuinfo failures (Closes: #257)

### PR DESCRIPTION
**Pull request by avalentino**
This PR improves robustness against cpuinfo failures on not supported architectures.

TODO:
* [ ] Unit tests and/or doctests in docstrings
* [x] ``tox -e py38`` passes locally
* [ ] Docstrings and API docs for any new/modified user-facing classes and functions
* [ ] Changes documented in docs/release.rst
* [ ] ``tox -e docs`` passes locally
* [x] AppVeyor and Travis CI passes
* [x] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by avalentino** [comment]
OK, failures on osx seems to be not related to this PR: see Blosc/c-blosc@5fc66f7cdcff969b47332ed843be5f344a5543cc and Blosc/c-blosc@406f5960da86f0932bd3609dae0bc70d5c785919.

**Comment by dstansby** [comment]
Since https://github.com/zarr-developers/numcodecs/pull/280 has been merged, which solved https://github.com/zarr-developers/numcodecs/issues/257 I think this PR is now obsolete and can be closed?

**Comment by dstansby** [comment]
Thanks for the PR! Since it looks like the original issue is closed, I've closed this, but please do open more PRs if you spot more issues!

**Comment by avalentino** [comment]
Thanks @dstansby

**Pull request closed without merging**
