### PR TITLE
Use unittest.mock on Python 3.

### PR DESCRIPTION
**Pull request by QuLogic**
As in title; reduces the dependencies by one.

TODO:
* [N/A] Unit tests and/or doctests in docstrings
* [N/A] ``tox -e py37`` passes locally
* [N/A] ``tox -e py27`` passes locally
* [N/A] Docstrings and API docs for any new/modified user-facing classes and functions
* [N/A] Changes documented in docs/release.rst
* [ ] ``tox -e docs`` passes locally
* [x] AppVeyor and Travis CI passes
* [x] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by QuLogic** [comment]
If rtfd builds with Python 3, then `mock` can be dropped from the requirements there, but I don't know what it uses.

**Comment by jakirkham** [comment]
Thanks for the PR @QuLogic! Pushed a small commit to see if we can fix coverage. If it passes, happy to merge. Please ping me if I forget. 🙂

**Comment by jakirkham** [comment]
Not sure what is up with the coverage report. When drilling down into it, am seeing 100% on the individual files.

**Comment by jakirkham** [comment]
Thanks @QuLogic! 😄

**Pull request merged**
