### PR TITLE
Build docs using sphinx-rtd-theme

### PR DESCRIPTION
**Pull request by dstansby**
This updates the doc config to use the sphinx-rtd-theme to build the docs. This is the theme that readthedocs uses to build the docs, so this PR make sure that docs built locally mirror the look of the rendered docs on readthedocs.

TODO:

- [ ] Unit tests and/or doctests in docstrings
- [ ] Tests pass locally
- [ ] Docstrings and API docs for any new/modified user-facing classes and functions
- [ ] Changes documented in docs/release.rst
- [ ] Docs build locally
- [ ] GitHub Actions CI passes
- [ ] Test coverage to 100% (Codecov passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks. Launched workflows. (cc: @MSanKeys963)

**Comment by dstansby** [comment]
Just wanted to see if there was anything else for to do to finish off this PR/any comments to address?

**Review by MSanKeys963 — APPROVED** [review]

**Comment by MSanKeys963** [comment]
Thanks for sending the PR, @dstansby.
I think we're good to go with this.

CC: @jakirkham

**Comment by joshmoore** [comment]
https://github.com/zarr-developers/numcodecs/pull/485 updated to pydata theme based on https://blog.readthedocs.com/defaulting-latest-build-tools/

@dstansby, does that work for you as well?

**Comment by dstansby** [comment]
Sure, I'll close this PR

**Comment by joshmoore** [comment]
Cheers

**Comment by jakirkham** [comment]
Ah sorry! Didn't see this one. Zarr had moved away from the RTD to the PyData theme. As there were some theme issues that cropped up recently with Numcodecs docs, went ahead and fixed those by moving Numcodecs to the PyData theme as well to make them consistent

**Pull request closed without merging**
