### PR TITLE
Changelog for 0.14.1

### PR DESCRIPTION
**Pull request by dstansby**
I thought it would be good to get these changes out sooner rather than later, given the changes to crc32c handling are breaking. @jakirkham I expanded on the changelog entry a bit to make it clear why the change was made, and more specifically what the change was.

### CODE REVIEW

**Comment by slevang** [comment]
#639 should be good to go, would be nice to get that in as well.

**Comment by jakirkham** [comment]
@slevang believe the goal here is to make a simple bug fix release

We can follow up on enhancements in a subsequent release

Hope that makes sense 🙂

**Comment by dstansby** [comment]
Yeah, I think we just want to get out the fix/change to `crc32c` here. I will take a look at #639 though, and we can do a new 0.15.0 release when that's merged.

**Comment by jakirkham** [comment]
Thanks David! 🙏

**Pull request merged**
