### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by joshmoore**
Following on from #224, these are the steps I'm assuming are required for a release with the wheels (feedback _very_ welcome):

 - [x] Bump minor version due to the drop of Python 2
 - [x] Bump docs/release.rst
 - If manual:
   - [ ] Tag & push to trigger wheel build
   - [ ] Wait on wheels to build then download
   - [ ] Extend the instructions in release.txt in upload the sdist as well as the wheels.
 - Or for an automatic deploy:
   - [x] introduce new PyPI user ("zarr_dev") for uploading.
   - [x] Introduce a new GitHub workflow to perform the above.
   - [ ] (Optionally merge PR and) push v0.7.0.rc1 tag to test push to pypi
   - [ ] Push v0.7.0 tag and hope for an automated release 🤞

### CODE REVIEW

**Comment by joshmoore** [comment]
* Migrated to tox for all build steps.
 * Added GHA steps for uploading to pypi.

If there are no objections, I'd propose to follow the "automatic deploy" checklist above once this PR has gone green.

cc: @jakirkham @alimanfoo @jrbourbeau

**Comment by jakirkham** [comment]
No objections from me. Are we handling all supported Python versions?

**Comment by joshmoore** [comment]
The current list of files in the download is:
```
1.2M numcodecs-0.6.5.dev15-cp35-cp35m-macosx_10_9_x86_64.whl
5.2M numcodecs-0.6.5.dev15-cp35-cp35m-manylinux1_i686.whl
5.5M numcodecs-0.6.5.dev15-cp35-cp35m-manylinux1_x86_64.whl
5.2M numcodecs-0.6.5.dev15-cp35-cp35m-manylinux2010_i686.whl
5.5M numcodecs-0.6.5.dev15-cp35-cp35m-manylinux2010_x86_64.whl
590K numcodecs-0.6.5.dev15-cp35-cp35m-win32.whl
680K numcodecs-0.6.5.dev15-cp35-cp35m-win_amd64.whl
1.2M numcodecs-0.6.5.dev15-cp36-cp36m-macosx_10_9_x86_64.whl
5.3M numcodecs-0.6.5.dev15-cp36-cp36m-manylinux1_i686.whl
5.5M numcodecs-0.6.5.dev15-cp36-cp36m-manylinux1_x86_64.whl
5.3M numcodecs-0.6.5.dev15-cp36-cp36m-manylinux2010_i686.whl
5.5M numcodecs-0.6.5.dev15-cp36-cp36m-manylinux2010_x86_64.whl
597K numcodecs-0.6.5.dev15-cp36-cp36m-win32.whl
689K numcodecs-0.6.5.dev15-cp36-cp36m-win_amd64.whl
1.2M numcodecs-0.6.5.dev15-cp37-cp37m-macosx_10_9_x86_64.whl
5.3M numcodecs-0.6.5.dev15-cp37-cp37m-manylinux1_i686.whl
5.6M numcodecs-0.6.5.dev15-cp37-cp37m-manylinux1_x86_64.whl
5.3M numcodecs-0.6.5.dev15-cp37-cp37m-manylinux2010_i686.whl
5.6M numcodecs-0.6.5.dev15-cp37-cp37m-manylinux2010_x86_64.whl
593K numcodecs-0.6.5.dev15-cp37-cp37m-win32.whl
689K numcodecs-0.6.5.dev15-cp37-cp37m-win_amd64.whl
1.2M numcodecs-0.6.5.dev15-cp38-cp38-macosx_10_9_x86_64.whl
5.4M numcodecs-0.6.5.dev15-cp38-cp38-manylinux1_i686.whl
5.7M numcodecs-0.6.5.dev15-cp38-cp38-manylinux1_x86_64.whl
5.4M numcodecs-0.6.5.dev15-cp38-cp38-manylinux2010_i686.whl
5.7M numcodecs-0.6.5.dev15-cp38-cp38-manylinux2010_x86_64.whl
602K numcodecs-0.6.5.dev15-cp38-cp38-win32.whl
694K numcodecs-0.6.5.dev15-cp38-cp38-win_amd64.whl
```

**Comment by jakirkham** [comment]
Looks good :)

**Comment by joshmoore** [comment]
Thanks, @jakirkham.

```
$ conda activate py38
(py38) $ python -m venv /tmp/test
(test) (py38) $ . /tmp/test/bin/activate 
(test) (py38) $ pip install --pre numcodecs
Collecting numcodecs
  Using cached https://files.pythonhosted.org/packages/86/e2/530c8c9c5ecedd45e79b0ba13e33059bb6340699e701badfd205cc159f27/numcodecs-0.7.0rc1.tar.gz
Collecting numpy>=1.7 (from numcodecs)
  Downloading https://files.pythonhosted.org/packages/ad/0b/c8b1383f0c43eabf925172ce850bf2224ede9fc351e8acf0ddd66ff567ff/numpy-1.19.1-cp37-cp37m-macosx_10_9_x86_64.whl (15.3MB)
     |████████████████████████████████| 15.3MB 447kB/s
Installing collected packages: numpy, numcodecs
  Running setup.py install for numcodecs ... done
Successfully installed numcodecs-0.7.0rc1 numpy-1.19.1
``` 
:+1: Pushing `v0.7.0`

**Comment by jakirkham** [comment]
Neat! So did it wind up pushing the wheels from CI as intended?

**Comment by jakirkham** [comment]
Unfortunately it seems the packages had some issues as reported in issue ( https://github.com/zarr-developers/numcodecs/issues/242 ). Went ahead and yanked them short term. Guess we need to dig into this a bit more still.

**Comment by joshmoore** [comment]
Thanks, agreed. (Sorry for having gone to sleep...) I'll work on a next PR to push to testpy instead otherwise on the release of 0.7.1 we'd need to re-yank.

**Comment by jakirkham** [comment]
No worries. Sleep is a good thing 🙂

Thanks Josh! Please let me know if you need another pair of eyes

**Comment by nbren12** [comment]
Thanks for working so hard on this @joshmoore. As a user of this package, I really appreciate the effort, and I am super excited to use the shiny new wheels once they are working.

**Comment by joshmoore** [comment]
Thanks go to @Czaki. I think we're all quite excited. ;)

**Pull request merged**
