### PR TITLE
Return `ndarray`s from `encode` and (where possible) `decode`

### PR DESCRIPTION
**Pull request by jakirkham**
Ensures binary `encode` functions return `ndarray`s generally. This makes the output easier to anticipate and work with. Also allows more unusual outputs like objects' internal buffers to be exposed in a friendly way to end users (while avoiding copying). Where possible also ensure `decode` functions return `ndarray`s.

TODO:
* [x] Unit tests and/or doctests in docstrings
* [x] ``tox -e py37`` passes locally
* [x] ``tox -e py27`` passes locally
* [x] Docstrings and API docs for any new/modified user-facing classes and functions
* [x] Changes documented in docs/release.rst
* [x] ``tox -e docs`` passes locally
* [x] AppVeyor and Travis CI passes
* [x] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Please let me know how you want this listed in the changelog (if at all).

**Comment by jakirkham** [comment]
Great, thanks for doing that, @alimanfoo. SGTM

**Comment by jakirkham** [comment]
Apologies for not opening a new issue for this. Happy to do so if needed.

Should we cut the release now or were there some other things still needed?

**Comment by alimanfoo** [comment]
No problem at all. I think cut the release now: #137.

**Pull request merged**
