### PR TITLE
Migrate from LGTM.com to GitHub code analysis

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
LGTM.com is being deprecated and replaced by GitHub code analysis:
[The next step for LGTM.com: GitHub code scanning!](https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/)

* Remove the deprecated `.lgtm.yml` configuration file.
* Initialize a configuration file `.github/workflows/codeql-analysis.yml`using the template provided in the [GitHub Action documentation](https://github.com/github/codeql-action#usage).
* Adapt the the template in `.github/workflows/codeql-analysis.yml` to  this specific package.

- [ ] Unit tests and/or doctests in docstrings
- [ ] `tox -e py310` passes locally
- [ ] Docstrings and API docs for any new/modified user-facing classes and functions
- [ ] Changes documented in docs/release.rst
- [ ] `tox -e docs` passes locally
- [x] GitHub Actions CI passes
- [x] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by joshmoore** [comment]
Is there anyway to get this to run within conda, @DimitriPapadopoulos?

**Comment by DimitriPapadopoulos** [comment]
You mean getting the GitHub Code Scanning Action to use Conda? I doubt that's feasible, and I want to avoid touching Conda myself – don't want to risk having to pay a licence.

Not sure how to fix these issues, will trying to downgrade [cpuinfo](https://github.com/workhorsy/py-cpuinfo) in requirements among other things:
```
   + python setup.py build
  /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
    warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
  Traceback (most recent call last):
    File "setup.py", line 4, in <module>
      import cpuinfo
  ModuleNotFoundError: No module named 'cpuinfo'
```

**Comment by jakirkham** [comment]
Interesting would have thought PR ( https://github.com/zarr-developers/numcodecs/pull/373 ) would have solved this. Maybe we need to start adding `tomli` in more places?

**Comment by DimitriPapadopoulos** [comment]
You mean adding `cpuinfo` in more places, like `requirements_test.txt`?

**Comment by jakirkham** [comment]
Was more thinking that in older Python versions we may need the backport package for TOML parsing. Otherwise it may be unable to discover build requirements and the like. Though could be wrong about that

**Comment by DimitriPapadopoulos** [comment]
I have (temporarily)added `tomli`  to `pyproject.toml` and it does help, thank you.

You will be adding `"setuptools_scm[toml]>=6.2"` any way in #382. I will try adding the same instead of `tomli`.

**Comment by DimitriPapadopoulos** [comment]
It looks like `setuptools_scm[toml]` in `pyproject.toml` is enough to get setuptools to pull dependecies from `pyproject.toml` itself.

**Comment by joshmoore** [comment]
Thanks, @DimitriPapadopoulos!

**Comment by jakirkham** [comment]
Thanks for figuring this out Dimitri! 🙏

**Comment by DimitriPapadopoulos** [comment]
I suggest you merge #382 first, then I can rebase to take advantage of this addition:
```
"setuptools-scm[toml]>=6.2",
```

**Comment by joshmoore** [comment]
Anything you need with this and #382 merged, @DimitriPapadopoulos ?

**Comment by jakirkham** [comment]
That's enabled here too

**Pull request merged**
