### PR TITLE
Add pypy build

### PR DESCRIPTION
**Pull request by Czaki**
[Description of PR]
This PR enables build pypy Wheel. But pypy wheel fail test and I do not know what should be fixed.

@jakirkham

TODO:
* [ ] Unit tests and/or doctests in docstrings
* [ ] ``tox -e py38`` passes locally
* [ ] Docstrings and API docs for any new/modified user-facing classes and functions
* [ ] Changes documented in docs/release.rst
* [ ] ``tox -e docs`` passes locally
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by Czaki** [comment]
This PR also enable wheel for CPython 3.9

**Comment by joshmoore** [comment]
@Czaki : do you want to re-remove ci-osx.yml here to speed up your builds?

**Comment by Czaki** [comment]
I could but I do not know how to fix to past test. And do not have time to do this now. 
If anyone else have time then he could bing `cibuildwheel` configuration from here and investigate time. 

It looks like now `numcodecs` is not compatible with `pypy`

**Comment by jakirkham** [comment]
Have made a few fixes to Numcodecs. Let's see if that fixes the CI here 🍀

**Comment by Czaki** [comment]
failed :( 
Disable some build?

**Comment by jakirkham** [comment]
Yeah I think there's some more debugging needed in the C extensions. Will work on it locally and update.

**Comment by dstansby** [comment]
Can this be closed in favour of https://github.com/zarr-developers/numcodecs/pull/409? (which seems more up to date)

**Comment by jakirkham** [comment]
Am not aware that either of these is being worked on

Perhaps we should close both

**Comment by dstansby** [comment]
👍 I'll close both since they're quite out of date and it's probably easier to start from scratch than fixing merge conflicts.

**Pull request closed without merging**
