### PR TITLE
Enable C-extensions on PyPy

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/zarr-developers/numcodecs/issues/238

Enables C-extensions support on PyPy (Cython support on PyPy has come a long ways). Also adds a [Travis CI job for PyPy]( https://docs.travis-ci.com/user/languages/python/#pypy-support ). Appears [AppVeyor does not officially support PyPy yet]( https://www.appveyor.com/docs/lang/python/#testing-against-pypy ). Haven't dug into how to do this on GitHub Workflows. Another question here would be building wheels for PyPy (maybe @Czaki has thoughts? 🙂).

TODO:
* [ ] Unit tests and/or doctests in docstrings
* [ ] ``tox -e py38`` passes locally
* [ ] Docstrings and API docs for any new/modified user-facing classes and functions
* [ ] Changes documented in docs/release.rst
* [ ] ``tox -e docs`` passes locally
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs PR ( https://github.com/zarr-developers/numcodecs/pull/245 ).

**Comment by Czaki** [comment]
@jakirkham I create #248 to enable pypy wheel build but it looks like pypy is not full supported (tests fail)

**Comment by jakirkham** [comment]
Great! Thanks for doing that Grzegorz 😄

Yeah I think our Cython version is out-of-date. There might be some other small tweaks after fixing that. Happy to handle those 🙂

**Comment by Czaki** [comment]
> Great! Thanks for doing that Grzegorz smile
> 
> Yeah I think our Cython version is out-of-date. There might be some other small tweaks after fixing that. Happy to handle those slightly_smiling_face

I regenerate regenerate c files using newest cython

**Pull request closed without merging**
