### PR TITLE
disable avx2 for wheel 

### LINKED ISSUE #252: Illegal instruction (core dumped) with version 0.7.1
#### Minimal, reproducible code sample, a copy-pastable example if possible

```
root@248fe153186d:/home/dash# python3
Python 3.8.2 (default, Apr 23 2020, 14:32:57)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numcodecs
Illegal instruction (core dumped)
```

#### Problem description

On a slightly older machine I get the above error when importing numcodecs. Does not happen with version 0.6.4 (the last non-yanked version prior to 0.7.1). 

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__`` 0.7.1
* Version of Python interpreter 3.8.2
* Operating system (Linux/Windows/Mac) Linux
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda") `pip3 install numcodecs`

Also, if you think it might be relevant, please provide the output from ``pip list`` or
``conda list`` depending on which was used to install NumCodecs.

Could this be related to #67 in that maybe this machine does not have the AVX instruction set?

### PR DESCRIPTION
**Pull request by Czaki**
Fixes #252 (illegal core dump)

### CODE REVIEW

**Comment by jakirkham** [comment]
LGTM. Thanks Grzegorz! 😄

**Comment by joshmoore** [comment]
@Czaki : any reason for this to still be in "draft" mode? Otherwise, I'd propose releasing 0.7.2

**Comment by Czaki** [comment]
> @Czaki : any reason for this to still be in "draft" mode? Otherwise, I'd propose releasing 0.7.2

Enabled avx2 on Macos and timezone. I live in Europe and already wake up.

**Comment by joshmoore** [comment]
:smile: Ditto. :+1:

**Comment by jakirkham** [comment]
I'm a bit of a night owl. So it works out 😄

Thanks again Grzegorz!

Should we try a patch release after this gets merged? 😉

**Comment by joshmoore** [comment]
Everything looks good. I'm merging, but I'll try to get in the Base64 fixture that John requested a review on. I assume 0.7.2 will go out over the course of the European morning unless I hear objections. Thanks all!

**Comment by jakirkham** [comment]
Thanks Josh! 😄

**Pull request merged**
