### PR TITLE
Remove LegacyMsgPack codec

### LINKED ISSUE #217: Dropping `LegacyMsgPack`
We ran into some issues with `LegacyMsgPack` and `msgpack-python` 1.0.0+ recently. In particular they came up in an attempt update the `numcodecs` feedstock ( https://github.com/conda-forge/numcodecs-feedstock/pull/48 ). Though presumably they exist in the wild as well. This raises the question of when do we want to drop `LegacyMsgPack`. Thoughts?

cc @jrbourbeau

### PR DESCRIPTION
**Pull request by jrbourbeau**
Closes #217

TODO:
* [ ] Unit tests and/or doctests in docstrings
* [ ] ``tox -e py38`` passes locally
* [ ] ``tox -e py27`` passes locally
* [ ] Docstrings and API docs for any new/modified user-facing classes and functions
* [ ] Changes documented in docs/release.rst
* [ ] ``tox -e docs`` passes locally
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks James! Looks good. 😀

Do we know what’s up with the coverage?

**Comment by jrbourbeau** [comment]
The coverage decrease looks to be coming from the Python 2.7 CI build not passing and contributing it's portion to coverage (e.g. https://coveralls.io/builds/29639832/source?filename=numcodecs%2Fcompat.py#L15). 

I'll submit a PR removing Python 2 support and that should fix things : )

**Comment by jakirkham** [comment]
Ah ok. Yeah that makes sense. Let's get that in first so we can get CI into a working state 🙂

**Comment by jakirkham** [comment]
Could you please resolve the conflicts here James? 🙂

**Comment by jrbourbeau** [comment]
Merge conflicts resolved. I also went ahead and removed the test `fixture` files associated with `LegacyMsgPack`

**Comment by jakirkham** [comment]
Thanks James! 😄

**Pull request merged**
